### ISSUE TITLE
publish the nextcloud:fpm tag too

### ISSUE THREAD

**Issue by realies** [kilrah/docker-templates#3]
i've been doing some nextcloud optimisations on one instance, and have found that things are running faster if i reduce the web server layers;

would you be able to also publish the official `:fpm` tag in your docker hub repository? it might be a matter of patching `FROM nextcloud` to FROM `nextcloud:fpm` and reconfiguring your deployment automation

**Comment by realies** [comment]
apparently, ffmpeg is already part of the image: https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/fpm/Dockerfile

**Comment by realies** [comment]
well, it is in the link i posted above, but not in what gets published in docker hub: https://hub.docker.com/layers/library/nextcloud/fpm/images/sha256-6264ce4a0ac53eff0257eb544374fbf17fde3e7796ad0b5f6deb965716d4b25f?context=explore

```
www-data@f80585a84960:~$ ffmpeg
bash: ffmpeg: command not found
```

**Comment by kilrah** [comment]
I've just pushed 28.0.2 as a test but since I don't have a setup to test it I probably won't make this a standard distro...

**Comment by realies** [comment]
not sure what you mean by making it a standard distro, but it works great; hope you keep the tag with future base image updates

**Comment by kilrah** [comment]
That's what I meant, I don't expect to keep building and pushing it if I can't check it, and I don't currently have an automated build so it's more steps to do.

**Comment by realies** [comment]
Can you leave it on automatic? I will be using this image on a few instances.

**Comment by kilrah** [comment]
As I said I don't currently have any build automation.

**Comment by realies** [comment]
Are you really pushing updates manually every time?

**Comment by kilrah** [comment]
Yup, just 2 builds once a month so meh, haven't bothered trying to find out a way to automate only the meaningful tags.

**Comment by realies** [comment]
i've just published a workflow and a script that does this, feel free to use them: https://github.com/realies/nextcloud-docker
